export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GOT_NEW_POST = 'GOT_NEW_POST'
export const UPDATE_POST_VOTESCORE = 'UPDATE_POST_VOTESCORE'
export const REMOVE_POST = 'REMOVE_POST'

export const UPDATE_NEW_POST = 'UPDATE_NEW_POST'
export const RESET_NEW_POST = 'RESET_NEW_POST'

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'

export const GET_POST_COMMENTS = 'GET_POST_COMMENTS'
export const UPDATE_COMMENT_VOTESCORE = 'UPDATE_COMMENT_VOTESCORE'
export const GOT_NEW_COMMENT = 'GOT_NEW_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

export const CHANGE_POST_ORDER = 'CHANGE_POST_ORDER'
export const CHANGE_POST = 'CHANGE_POST'